/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GbcButton {
        "type": string;
    }
    interface GbcInput {
        "type": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGbcButtonElement extends Components.GbcButton, HTMLStencilElement {
    }
    var HTMLGbcButtonElement: {
        prototype: HTMLGbcButtonElement;
        new (): HTMLGbcButtonElement;
    };
    interface HTMLGbcInputElement extends Components.GbcInput, HTMLStencilElement {
    }
    var HTMLGbcInputElement: {
        prototype: HTMLGbcInputElement;
        new (): HTMLGbcInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "gbc-button": HTMLGbcButtonElement;
        "gbc-input": HTMLGbcInputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface GbcButton {
        "type"?: string;
    }
    interface GbcInput {
        "type"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "gbc-button": GbcButton;
        "gbc-input": GbcInput;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gbc-button": LocalJSX.GbcButton & JSXBase.HTMLAttributes<HTMLGbcButtonElement>;
            "gbc-input": LocalJSX.GbcInput & JSXBase.HTMLAttributes<HTMLGbcInputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
