/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * Do __not__ import components from this file as server side rendered components
 * may not hydrate due to missing Stencil runtime. Instead, import these components through the generated 'components.ts'
 * file that re-exports all components with the 'use client' directive.
 */

/* eslint-disable */

import { GbcButton as GbcButtonElement, defineCustomElement as defineGbcButton } from "@guilhermebc/gbc-design-system-core/dist/components/gbc-button.js";
import { GbcInput as GbcInputElement, defineCustomElement as defineGbcInput } from "@guilhermebc/gbc-design-system-core/dist/components/gbc-input.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "@guilhermebc/gbc-design-system-core/dist/components/my-component.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent, createSSRComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type GbcButtonEvents = NonNullable<unknown>;

export const GbcButton: StencilReactComponent<GbcButtonElement, GbcButtonEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<GbcButtonElement, GbcButtonEvents>({
        tagName: 'gbc-button',
        elementClass: GbcButtonElement,
        react: React,
        events: {} as GbcButtonEvents,
        defineCustomElement: defineGbcButton
    })
    : /*@__PURE__*/ createSSRComponent<GbcButtonElement, GbcButtonEvents>({
        tagName: 'gbc-button',
        hydrateModule: import('@guilhermebc/gbc-design-system-core/hydrate')
    });

type GbcInputEvents = NonNullable<unknown>;

export const GbcInput: StencilReactComponent<GbcInputElement, GbcInputEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<GbcInputElement, GbcInputEvents>({
        tagName: 'gbc-input',
        elementClass: GbcInputElement,
        react: React,
        events: {} as GbcInputEvents,
        defineCustomElement: defineGbcInput
    })
    : /*@__PURE__*/ createSSRComponent<GbcInputElement, GbcInputEvents>({
        tagName: 'gbc-input',
        hydrateModule: import('@guilhermebc/gbc-design-system-core/hydrate')
    });

type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = typeof window !== 'undefined'
    ? /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
        tagName: 'my-component',
        elementClass: MyComponentElement,
        react: React,
        events: {} as MyComponentEvents,
        defineCustomElement: defineMyComponent
    })
    : /*@__PURE__*/ createSSRComponent<MyComponentElement, MyComponentEvents>({
        tagName: 'my-component',
        hydrateModule: import('@guilhermebc/gbc-design-system-core/hydrate')
    });
